import { ROLES, KYC_STATUS, REQUEST_STATUS, SERVICE_TYPES, URGENCY } from '../constants';

export const SEED_MEMBERS = [
  {
    id: 'sen-1',
    name: 'Smt. Shanti Devi',
    role: ROLES.SENIOR,
    roles: [ROLES.SENIOR],
    active_role: ROLES.SENIOR,
    age: 74,
    dob: '1952-04-12',
    phone: '+919820123456',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    created_at: '2026-01-10T10:00:00Z',
    member_since: '2026-01',
  },
  {
    id: 'sen-2',
    name: 'Shri Rameshwar Prasad',
    role: ROLES.SENIOR,
    roles: [ROLES.SENIOR],
    active_role: ROLES.SENIOR,
    age: 78,
    dob: '1948-08-25',
    phone: '+919820234567',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    created_at: '2026-02-01T11:30:00Z',
    member_since: '2026-02',
  },
  {
    id: 'sen-3',
    name: 'Smt. Sunita Sharma',
    role: ROLES.SENIOR,
    roles: [ROLES.SENIOR],
    active_role: ROLES.SENIOR,
    age: 69,
    dob: '1957-11-05',
    phone: '+919820345678',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    created_at: '2026-02-15T09:15:00Z',
    member_since: '2026-02',
  },
  {
    id: 'sen-4',
    name: 'Shri K. L. Narayanan',
    role: ROLES.SENIOR,
    roles: [ROLES.SENIOR],
    active_role: ROLES.SENIOR,
    age: 81,
    dob: '1945-03-18',
    phone: '+919820456789',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    created_at: '2026-03-01T08:00:00Z',
    member_since: '2026-03',
  },
  {
    id: 'vol-1',
    name: 'Aarav Sharma',
    role: ROLES.VOLUNTEER,
    roles: [ROLES.VOLUNTEER],
    active_role: ROLES.VOLUNTEER,
    age: 24,
    dob: '2002-06-14',
    phone: '+919819111222',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    availability: 'ready',
    created_at: '2026-01-15T14:20:00Z',
    member_since: '2026-01',
  },
  {
    id: 'vol-2',
    name: 'Priya Patel',
    role: ROLES.VOLUNTEER,
    roles: [ROLES.VOLUNTEER],
    active_role: ROLES.VOLUNTEER,
    age: 27,
    dob: '1999-09-20',
    phone: '+919819222333',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    availability: 'ready',
    created_at: '2026-02-10T16:00:00Z',
    member_since: '2026-02',
  },
  {
    id: 'vol-3',
    name: 'Vikram Malhotra',
    role: ROLES.VOLUNTEER,
    roles: [ROLES.VOLUNTEER],
    active_role: ROLES.VOLUNTEER,
    age: 32,
    dob: '1994-12-01',
    phone: '+919819333444',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    availability: 'busy',
    created_at: '2026-03-05T12:00:00Z',
    member_since: '2026-03',
  },
  {
    id: 'vol-4',
    name: 'Ananya Iyer',
    role: ROLES.VOLUNTEER,
    roles: [ROLES.VOLUNTEER],
    active_role: ROLES.VOLUNTEER,
    age: 22,
    dob: '2004-02-18',
    phone: '+919880112233',
    pincode: '560001',
    area: 'MG Road, Bengaluru',
    city: 'Bengaluru',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    availability: 'ready',
    created_at: '2026-01-20T10:00:00Z',
    member_since: '2026-01',
  },
  {
    id: 'vol-5',
    name: 'Rohan Verma',
    role: ROLES.VOLUNTEER,
    roles: [ROLES.VOLUNTEER],
    active_role: ROLES.VOLUNTEER,
    age: 29,
    dob: '1997-07-09',
    phone: '+919811223344',
    pincode: '110001',
    area: 'Connaught Place, New Delhi',
    city: 'New Delhi',
    kyc_status: KYC_STATUS.VERIFIED,
    is_blocked: false,
    availability: 'ready',
    created_at: '2026-02-12T09:00:00Z',
    member_since: '2026-02',
  },
  // Pincode Admin Applicant waiting for Super Admin approval
  {
    id: 'adm-app-1',
    name: 'Meera Deshmukh',
    role: ROLES.VOLUNTEER,
    roles: ['volunteer', 'admin'],
    active_role: 'volunteer',
    age: 35,
    phone: '+919820567890',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.VERIFIED,
    pincode_admin_approved: false,
    is_blocked: false,
    created_at: '2026-03-10T14:00:00Z',
    member_since: '2026-03',
  },
  // Pending KYC users
  {
    id: 'pend-1',
    name: 'Harish Chandra Gupta',
    role: ROLES.SENIOR,
    roles: [ROLES.SENIOR],
    active_role: ROLES.SENIOR,
    age: 72,
    phone: '+919820678901',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.PENDING,
    document_type: 'Aadhaar',
    aadhaar_last4: '4819',
    submitted_on: '2026-09-20T14:30:00Z',
    created_at: '2026-09-20T14:30:00Z',
    notes: 'Senior citizen seeking volunteer assistance for weekly grocery and clinic trips.',
  },
  {
    id: 'pend-2',
    name: 'Neha Joshi',
    role: ROLES.VOLUNTEER,
    roles: [ROLES.VOLUNTEER],
    active_role: ROLES.VOLUNTEER,
    age: 23,
    phone: '+919819444555',
    pincode: '400001',
    area: 'Colaba, Mumbai',
    city: 'Mumbai',
    kyc_status: KYC_STATUS.PENDING,
    document_type: 'Aadhaar',
    aadhaar_last4: '9234',
    submitted_on: '2026-09-21T09:10:00Z',
    created_at: '2026-09-21T09:10:00Z',
    notes: 'Graduate student wanting to provide technology and companionship seva.',
  },
];

const now = new Date();
const isoToday = now.toISOString();
const isoYesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString();
const iso2DaysAgo = new Date(now.getTime() - 48 * 60 * 60 * 1000).toISOString();
const iso5DaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString();
const iso8DaysAgo = new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString();

export const SEED_REQUESTS = [
  // 1. CREATED (Open request created by Admin on behalf of Senior)
  {
    id: 'req-seed-1',
    seniorId: 'sen-1',
    seniorName: 'Smt. Shanti Devi',
    serviceType: SERVICE_TYPES.MEDICINE,
    description: 'Senior needs monthly BP and diabetic tablets fetched from Colaba Pharmacy.',
    location: 'Colaba Market, Mumbai',
    pincode: '400001',
    urgency: URGENCY.HIGH,
    status: REQUEST_STATUS.OPEN,
    lifecycleStatus: 'created',
    scheduledDate: 'Today, 4:00 PM',
    scheduledTime: '16:00',
    estimatedDuration: 30,
    createdByAdminId: 'admin-1',
    createdByAdminName: 'Pincode Admin Team',
    createdAt: isoToday,
  },
  // 2. NOTIFIED_TRUSTED (Notified to trusted circle volunteers first)
  {
    id: 'req-seed-2',
    seniorId: 'sen-2',
    seniorName: 'Shri Rameshwar Prasad',
    serviceType: SERVICE_TYPES.GROCERIES,
    description: 'Fresh milk, wheat flour, and vegetables from local market.',
    location: 'Cuffe Parade, Colaba',
    pincode: '400001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.NOTIFIED_TRUSTED,
    lifecycleStatus: 'notified_trusted',
    scheduledDate: 'Tomorrow Morning',
    scheduledTime: '09:00',
    estimatedDuration: 45,
    notifiedAt: isoToday,
    createdAt: isoToday,
  },
  // 3. ACCEPTED (Assigned to Aarav Sharma, awaiting task commencement)
  {
    id: 'req-seed-3',
    seniorId: 'sen-4',
    seniorName: 'Shri K. L. Narayanan',
    serviceType: SERVICE_TYPES.BANK,
    description: 'Accompaniment to State Bank of India branch for annual life certificate verification.',
    location: 'SBI Colaba Branch',
    pincode: '400001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.ACCEPTED,
    lifecycleStatus: 'accepted',
    assignedVolunteerId: 'vol-1',
    assignedVolunteerName: 'Aarav Sharma',
    scheduledDate: 'Tomorrow, 11:00 AM',
    scheduledTime: '11:00',
    estimatedDuration: 60,
    createdAt: isoYesterday,
  },
  // 4. IN_PROGRESS (Currently active session with Priya Patel)
  {
    id: 'req-seed-4',
    seniorId: 'sen-1',
    seniorName: 'Smt. Shanti Devi',
    serviceType: SERVICE_TYPES.WALK,
    description: 'Assisted evening walk and companionship at Colaba Woods garden.',
    location: 'Colaba Woods, Mumbai',
    pincode: '400001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.IN_PROGRESS,
    lifecycleStatus: 'in_progress',
    assignedVolunteerId: 'vol-2',
    assignedVolunteerName: 'Priya Patel',
    sessionStartedAt: isoToday,
    estimatedDuration: 45,
    createdAt: isoToday,
  },
  // 5. COMPLETED (Completed by Aarav Sharma, pending rating)
  {
    id: 'req-seed-5',
    seniorId: 'sen-1',
    seniorName: 'Smt. Shanti Devi',
    serviceType: SERVICE_TYPES.EMOTIONAL,
    description: 'Reading newspapers in Hindi and friendly companionship.',
    location: 'Near Sasoon Dock, Colaba',
    pincode: '400001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.COMPLETED,
    lifecycleStatus: 'completed',
    assignedVolunteerId: 'vol-1',
    assignedVolunteerName: 'Aarav Sharma',
    duration: 90,
    completedAt: isoYesterday,
    createdAt: isoYesterday,
  },
  // 6. RATED (Completed by Aarav Sharma, rated 5 stars by Shri Rameshwar Prasad)
  {
    id: 'req-seed-6',
    seniorId: 'sen-2',
    seniorName: 'Shri Rameshwar Prasad',
    serviceType: SERVICE_TYPES.OTHER,
    description: 'Help setting up smartphone video call with grandchildren in Bangalore.',
    location: 'Pasta Lane, Colaba',
    pincode: '400001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.RATED,
    lifecycleStatus: 'rated',
    assignedVolunteerId: 'vol-1',
    assignedVolunteerName: 'Aarav Sharma',
    duration: 60,
    completedAt: iso2DaysAgo,
    createdAt: iso2DaysAgo,
    rating: {
      stars: 5,
      review: 'आरव बहुत धैर्यवान और विनम्र हैं। उन्होंने बहुत अच्छे से फोन चलाना सिखाया।',
    },
  },
  // 7. CLOSED (Completed by Priya Patel, rated, and closed)
  {
    id: 'req-seed-7',
    seniorId: 'sen-4',
    seniorName: 'Shri K. L. Narayanan',
    serviceType: SERVICE_TYPES.MEDICINE,
    description: 'Urgent eye drops delivery from medical store.',
    location: 'Colaba Causeway',
    pincode: '400001',
    urgency: URGENCY.HIGH,
    status: REQUEST_STATUS.CLOSED,
    lifecycleStatus: 'closed',
    assignedVolunteerId: 'vol-2',
    assignedVolunteerName: 'Priya Patel',
    duration: 60,
    completedAt: iso5DaysAgo,
    createdAt: iso5DaysAgo,
    rating: {
      stars: 5,
      review: 'Very punctual and brought exactly the prescribed eye drops.',
    },
  },
  // 8. CANCELLED
  {
    id: 'req-seed-8',
    seniorId: 'sen-2',
    seniorName: 'Shri Rameshwar Prasad',
    serviceType: SERVICE_TYPES.GROCERIES,
    description: 'Grocery store assistance (cancelled by family members visiting).',
    location: 'Colaba Post Office area',
    pincode: '400001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.CANCELLED,
    lifecycleStatus: 'cancelled',
    createdAt: iso8DaysAgo,
  },
  // 9. All-India completed record: Bengaluru (Ananya Iyer)
  {
    id: 'req-seed-9',
    seniorId: 'sen-blr-1',
    seniorName: 'Smt. Padmavati Rao',
    serviceType: SERVICE_TYPES.BANK,
    description: 'Pension document submission at bank in Bengaluru.',
    location: 'MG Road, Bengaluru',
    pincode: '560001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.COMPLETED,
    lifecycleStatus: 'completed',
    assignedVolunteerId: 'vol-4',
    assignedVolunteerName: 'Ananya Iyer',
    duration: 120,
    completedAt: isoYesterday,
    createdAt: isoYesterday,
    rating: {
      stars: 5,
      review: 'Kind and very helpful volunteer!',
    },
  },
  // 10. All-India completed record: New Delhi (Rohan Verma)
  {
    id: 'req-seed-10',
    seniorId: 'sen-del-1',
    seniorName: 'Shri Balram Tyagi',
    serviceType: SERVICE_TYPES.MEDICINE,
    description: 'Delivery of diabetes supplies and walking help in New Delhi.',
    location: 'Connaught Place, New Delhi',
    pincode: '110001',
    urgency: URGENCY.NORMAL,
    status: REQUEST_STATUS.COMPLETED,
    lifecycleStatus: 'completed',
    assignedVolunteerId: 'vol-5',
    assignedVolunteerName: 'Rohan Verma',
    duration: 90,
    completedAt: iso2DaysAgo,
    createdAt: iso2DaysAgo,
    rating: {
      stars: 5,
      review: 'रोहन जी ने समय पर सेवा दी। धन्यवाद।',
    },
  },
];

export const SEED_RATINGS = [
  {
    id: 'rat-1',
    request_id: 'req-seed-6',
    reviewer_id: 'sen-2',
    reviewer_name: 'Shri Rameshwar Prasad',
    reviewee_id: 'vol-1',
    reviewee_name: 'Aarav Sharma',
    stars: 5,
    review: 'आरव बहुत धैर्यवान और विनम्र हैं। उन्होंने बहुत अच्छे से फोन चलाना सिखाया।',
    created_at: iso2DaysAgo,
  },
  {
    id: 'rat-2',
    request_id: 'req-seed-7',
    reviewer_id: 'sen-4',
    reviewer_name: 'Shri K. L. Narayanan',
    reviewee_id: 'vol-2',
    reviewee_name: 'Priya Patel',
    stars: 5,
    review: 'Very punctual and brought exactly the prescribed eye drops.',
    created_at: iso5DaysAgo,
  },
  {
    id: 'rat-3',
    request_id: 'req-seed-9',
    reviewer_id: 'sen-blr-1',
    reviewer_name: 'Smt. Padmavati Rao',
    reviewee_id: 'vol-4',
    reviewee_name: 'Ananya Iyer',
    stars: 5,
    review: 'Kind and very helpful volunteer!',
    created_at: isoYesterday,
  },
  {
    id: 'rat-4',
    request_id: 'req-seed-10',
    reviewer_id: 'sen-del-1',
    reviewer_name: 'Shri Balram Tyagi',
    reviewee_id: 'vol-5',
    reviewee_name: 'Rohan Verma',
    stars: 5,
    review: 'रोहन जी ने समय पर सेवा दी। धन्यवाद।',
    created_at: iso2DaysAgo,
  },
];
